### ISSUE TITLE
negative value for extra currency 

### ISSUE THREAD

**Issue by ShalokShalom** [billthefarmer/currency#71] opened 2021-06-15 12:46 UTC
When I type 0.001616 to add the Costa Rican currency, the app makes 1.616,000 out of it.

This way, no currency that is less worth than the dollar (I assume?) can be added.

The whole process of adding a new currency can be improved, since the menu "Update" is not really indicative for that.

**Comment by billthefarmer** [comment] 2021-06-16 12:21
I have looked at this, there are two problems, if you are in a locale that uses a comma as a decimal point, the keyboard input may not work properly, and even with 5 digits of accuracy, you can only get 0.00016. So, even if you set the value at the top to €1000, you get 0.16000. I will attempt to fix this and release a new version.

**Comment by billthefarmer** [comment] 2021-06-17 17:52
OK, that works, it will be in the next version.

![Screenshot_20210617-185040 1](https://user-images.githubusercontent.com/3448386/122448897-273c2400-cf9d-11eb-940b-03c8e387d876.png)

**Comment by ShalokShalom** [comment] 2021-06-17 18:06
Wow

Super fast

When can we hope that this version is available?

**Comment by billthefarmer** [comment] 2021-06-18 07:44
That's down to F-Droid, could take a week or so, or you could build it yourself.

**Comment by ShalokShalom** [comment] 2021-06-28 15:57
This is still the same, updated it just twice, same old issue:

![Screenshot_2021-06-28_09-56-33](https://user-images.githubusercontent.com/6344099/123667232-30c45800-d7f7-11eb-8a28-8a3171b572ca.png)
![Screenshot_2021-06-28_09-56-49](https://user-images.githubusercontent.com/6344099/123667239-328e1b80-d7f7-11eb-8dd1-1dc633c60f29.png)

**Comment by billthefarmer** [comment] 2021-06-29 12:17
I can't reproduce that. You appear to be using a full stop as a decimal point in a locale that uses a comma. Have you tried entering 0,001616 with a comma?

**Closed** 2021-07-09 19:56 UTC

**Comment by ShalokShalom** [comment] 2021-07-10 09:25
Yep, 0,001616 gives me this:

![Screenshot_2021-07-10_11-24-44](https://user-images.githubusercontent.com/6344099/125158445-8bec3800-e171-11eb-8789-1327f9699aea.png)
![Screenshot_2021-07-10_11-25-02](https://user-images.githubusercontent.com/6344099/125158447-8c84ce80-e171-11eb-81be-2395ec9e0838.png)
