### ISSUE TITLE
List of selcted currencies contains duplicates

### ISSUE THREAD

**Issue by ILoveFOSS** [billthefarmer/currency#72] opened 2021-08-02 06:17 UTC
Hi and thank you for this really handy app!

After installing it today, I found a small bug. The editable currency on the very top of the list gets duplicated if it is added to the list again. I discovered it while adding several currencies without checking which ones I added before. In the screenshot, you can see that all currencies can be added twice: ![signal-2021-08-02-080929](https://user-images.githubusercontent.com/81854757/127812485-c99ecb41-ff49-40b9-b640-411a74bf22e8.jpeg)

Regards!

**Comment by billthefarmer** [comment] 2021-08-02 12:25
That's not a bug, it's a feature because it's undoable. It's taken five years for someone to notice that. It will be fixed in the next version.

**Closed** 2021-08-29 17:58 UTC
